### ISSUE TITLE
Can't run query, 'query is not allowed'. Similar to previous issue, but fix not longer working...

### ISSUE THREAD

**Issue by 0x01001111** [itzmestar/duneanalytics#13]
Similar to previous issue, but fix not longer working...

**Comment by jerrycc21** [comment]
Fixed this issue in my fork. https://github.com/jerrycc21/duneanalytics/blob/main/duneanalytics/duneanalytics.py

**Comment by 0x01001111** [comment]
Been running the fix from your fork, "get_result_v2" right? But it's not working again...

**Comment by bayeshelsinki** [comment]
Yeah, I've been using the previous fix as well and so far no problem (thanks for the fix!), but 2 days ago the fix stopped working. I get the same error message: 'query is not allowed'.

**Comment by bayeshelsinki** [comment]
This problem vanished. The previous fix works again.

**Comment by itzmestar** [comment]
closing issue since its working
