### ISSUE TITLE
Login Failed!

### ISSUE THREAD

**Issue by mohammed7s** [itzmestar/duneanalytics#14]
Ran the following code in the README.me : 

`from duneanalytics import DuneAnalytics`

`dune = DuneAnalytics('username', 'password')`

`dune.login()`

`dune.fetch_auth_token()`

Got this output: 

2022-09-09 12:16:41,673 : WARNING : login     : Login Failed!
2022-09-09 12:16:41,804 : ERROR : fetch_auth_token : {}

Any idea why this is the case?

**Comment by syed1ahmed** [comment]
Replace 'username' & 'password' with your dune login credentials

**Comment by mohammed0x8** [comment]
I should have specified I am sorry. Yes I did that of course. I replaced with my credentials but still get the error.

**Comment by itzmestar** [comment]
i see login is working fine.
please uninstall & install again.
