### ISSUE TITLE
{"path":"$","error":"resource does not exist","code":"not-found"}

### ISSUE THREAD

**Issue by jordip6** [itzmestar/duneanalytics#15]
Since yesterday I'm receiving this message when I try to extract any query. Do you know which could be the problem? Some change in Dune or anything I need to update?

Thanks in advance

**Comment by syed1ahmed** [comment]
yup i am getting the same thing.
its most likely dune changed something on there end

**Comment by syed1ahmed** [comment]
Did any one find a fix for this issue?

**Comment by syed1ahmed** [comment]
okk..
I solved This Issue in my pull request #16
until that is merged u can refer my fork of duneanalytics

**Comment by jordip6** [comment]
It works, thanks a lot @syed1ahmed !!!

**Comment by kaionwong** [comment]
Thanks @syed1ahmed it works. The following is the import statement that works (prior to your git commit to be merged)

```
import duneanalytics.duneanalytics
# debugging note - https://github.com/itzmestar/duneanalytics/pull/16/commits/bc9319a3f3449732bc75e6a7e36c8cd35fc88bb0
duneanalytics.duneanalytics.GRAPH_URL = 'https://core-hsr.dune.com/v1/graphql'
from duneanalytics import DuneAnalytics
```
