### ISSUE TITLE
Dune has updated api to v3

### ISSUE THREAD

**Issue by Someletters** [itzmestar/duneanalytics#19]
Dune has updated api to v3, the pip may fail.

**Comment by DenisKochetov** [comment]
GM Sir @Someletters !
Could you please share new urls? If I get you right I should change these:

BASE_URL = "https://dune.com"
GRAPH_URL = 'https://core-hsr.dune.com/v1/graphql'

My discord acc: dddsb13#1833

**Comment by itzmestar** [comment]
i dont see any error. I am based in India.

**Comment by nethermind-joe** [comment]
> i dont see any error. I am based in India.

It works with old queries but new ones fail with that error :-(

**Comment by itzmestar** [comment]
Share few queries which are failing?

**Comment by nethermind-joe** [comment]
> Here is the query that seems to be falling and I have tried dune_query_result_id and it does not seem to return None with that query

<img width="365" alt="image" src="https://user-images.githubusercontent.com/108332246/203503363-a734fb49-6cc7-4d7c-aace-99ec33025af5.png">

**Comment by coindataschool** [comment]
Running `dune.query_result_id(1105079)` gives the following error:

`ERROR : query_result_id : [{'extensions': {'path': '$', 'code': 'validation-failed'}, 'message': 'query is not allowed'}]`

Here's the query on dune: https://dune.com/queries/1105079

**Comment by GoodSamoSamo** [comment]
any update @itzmestar?

**Comment by coindataschool** [comment]
It seems to be working now. Don't know why and what happened. Thanks for your awesome work!
