### ISSUE TITLE
API Is Broken, No Query Results Successful

### ISSUE THREAD

**Issue by GoodSamoSamo** [itzmestar/duneanalytics#20]
It seems like with the latest upgrade, this API is broken. I can't fetch the results of ANY query. I've even used a VPN.

Getting the same error for every query.

```ERROR : query_result_id : [{'extensions': {'path': '$', 'code': 'validation-failed'}, 'message': 'query is not allowed'}]```

**Comment by Lissanro** [comment]
I have the same issue. I could not find any workaround unfortunately.

**Comment by xtsun96** [comment]
Same here. Do not know if the author could help.

**Comment by mohammed7s** [comment]
Hello has anyone solved this?

**Comment by LinuxIsCool** [comment]
Some queries are working for me, but some are resulting in the above error. For example this one is failing: https://dune.com/queries/1898885/3125794

**Comment by GoodSamoSamo** [comment]
resolved
