### ISSUE TITLE
Issue with Login

### ISSUE THREAD

**Issue by ries9112** [itzmestar/duneanalytics#4]
This is just what I was looking for, thank you for making this package!

Unfortunately I can't get the login to work on my end:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/32306488/129742122-6ee5c8a6-4e48-4086-ac92-7e771f75de35.png">

When running `dune.fetch_auth_token()` I get the response `Method Not Allowed`. I am sure the credentials are correct. Do I need the Pro subscription? If not, what do you think the issue is?

**Comment by itzmestar** [comment]
Pro subscription is not required.
I tried with my credentials, it seems to be working fine.

**Comment by ries9112** [comment]
Thanks for the reply. Hmm weird, ok I will keep playing around with it. Having the same issue with the other implementation by another user as well, and must be my account.

I did have one other user DM me on twitter who seemed to be running into the same issues as me:
![image](https://user-images.githubusercontent.com/32306488/130357038-23d68a6e-b55b-48b3-94a8-531b7277ef3f.png)

**Comment by itzmestar** [comment]
After `dune.login()` please try to print `dune.auth_refresh` what does it give you?

Try to use another login to see it's working?

**Comment by RickyEsclapon** [comment]
Sorry for the slow response. When I run `dune.auth_refresh` nothing seems to happen. 

I created a new account and I'm getting the same issue:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/89109989/134692368-4797ffda-dafb-45a2-aeab-1c04d4acfded.png">

So just to confirm, there is nothing at all to do in terms of account setup outside of providing username & password?

Thanks for maintaining this really helpful package and looking forward to getting this working on my end

**Comment by itzmestar** [comment]
solved in latest version.

**Comment by Dominik1999** [comment]
This issue seems to be back, at least for me

**Comment by tina1998612** [comment]
Me too have the same issue :(

**Comment by Dominik1999** [comment]
Has anyone solved that yet?

**Comment by duykhangpham201** [comment]
Anyone knows how to solve it yet?
