### ISSUE TITLE
Auto-update the query result

### ISSUE THREAD

**Issue by andrewshvv** [itzmestar/duneanalytics#8]
When querying the data with this library it might take the direct data from the query. Sometimes it leads to the fact that old data is received, and we need manually go to the query and re-run it, in order to update the data. Is there any way to get the latest data without manual involvement?

For example, fetching data from such a query would result in receiving 46 minutes old data:
![image](https://user-images.githubusercontent.com/3414579/158599862-c295765e-8aa0-40ed-8cbf-e0d56a283100.png)

**Comment by mike-luabase** [comment]
@andrewshvv  what SQL are you running in Dune? If this is getting cumbersome, might be worth giving [Luabase](https://luabase.com/) a 👀 . We have a real API.

I'm the founder, give me a shout: mike@luabase.com
