### ISSUE TITLE
Cannot make any query: 'query not allowed'

### ISSUE THREAD

**Issue by cryptodatawizard** [itzmestar/duneanalytics#9]
Used the the library for the past week, worked like a charm. Now I can no longer make any successful queries, tried different old and new Dune account logins:

```
from duneanalytics import DuneAnalytics

# initialize client
login = *****
pwd = *****
dune = DuneAnalytics(login,  pwd)

# try to login
dune.login()

# fetch token
dune.fetch_auth_token()

result_id = dune.query_result_id(query_id=859357)

# fetch query result
data = dune.query_result(result_id)
```

output:

```
{'errors': [{'extensions': {'path': '$', 'code': 'validation-failed'}, 'message': 'query is not allowed'}]}
{'data': {'query_results': [], 'get_result_by_result_id': []}}
```

**Comment by SpruceGoose505** [comment]
Getting the same error on my end

**Comment by KKhushhalR2405** [comment]
If anyone gets any updates/fixes, please post them here. TIA

**Comment by jerrycc21** [comment]
Change `get_result` on lines 96 and 108 in file `duneanalytics.py` to `get_result_v2`.

**Comment by cryptodatawizard** [comment]
are you sure this fixes the problem ? I still have the same output with these changes

**Comment by jerrycc21** [comment]
Oh, I'm missed an item and you need to add another `error_id\n` on line 97. Like this
```
query_data = {"operationName": "GetResult", "variables": {"query_id": query_id},
                      "query": "query GetResult($query_id: Int!, $parameters: [Parameter!]) "
                               "{\n  get_result_v2(query_id: $query_id, parameters: $parameters) "
                               "{\n    job_id\n    result_id\n   error_id\n      __typename\n  }\n}\n"
                      }
```

**Comment by SpruceGoose505** [comment]
Can confirm, @jerrycc21's solutions works! Thank you

**Comment by cryptodatawizard** [comment]
Awesome ! Thanks a lot @jerrycc21
I'm new to postgresql, can you provide a hint to where you can track these
api changes to know how to adapt the queries ?
Any further docs/resources can be very helpful :)

**Comment by jerrycc21** [comment]
![image](https://user-images.githubusercontent.com/105102447/171338141-e8b4e279-e0d7-4e6e-8ad7-145ebb0384b9.png)
@cryptodatawizard

**Comment by cryptodatawizard** [comment]
Ah, I was close :) thanks a lot !

**Comment by cryptodatawizard** [comment]
@Jonny88765  if you can run the main python example, you can save the pandas DataFrame `data` using `data.to_csv("path/to/data.csv")` as a csv file which can be opened in excel

**Comment by KKhushhalR2405** [comment]
@Jonny88765  Just adding on @cryptodatawizard solution, you can use the following snippet. This is how I am doing it.

![image](https://user-images.githubusercontent.com/58569950/172684931-51edcd0f-ae27-4b18-837a-2cca8c2d93ad.png)

**Comment by itzmestar** [comment]
solved the issue.
Thanks for your patience.

**Comment by Jonny88765** [comment]
Hi again, and thanks a lot. Excel csv export is working now with the answer provided by @Jonny88765 and @cryptodatawizard!

**Comment by mike-luabase** [comment]
@Jonny88765 @cryptodatawizard  what SQL are you running in Dune? If this is getting cumbersome, might be worth giving [Luabase](https://luabase.com/) a 👀 . We have a real API.

I'm the founder, give me a shout: mike@luabase.com
